services:
  - type: web
    name: my-face-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve@latest out
    envVars:
      - key: NODE_ENV
        value: production
